# Contextualized Networks

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
X = np.random.normal(0, 1, size=(1000, 10))
C = np.random.uniform(-1, 1, size=(1000, 5))

In [3]:
# Correlation Networks
from contextualized.easy import ContextualizedCorrelationNetworks

ccn = ContextualizedCorrelationNetworks(encoder_type='ngam', num_archetypes=16, n_bootstraps=3)
ccn.fit(C, X, max_epochs=5)

# Get rho
ccn.predict_correlation(C, squared=False)

# Get rho^2
ccn.predict_correlation(C, squared=True)

GPU available: True (mps), used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
/opt/homebrew/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py:1789: UserWarning: MPS available but not used. Set `accelerator` and `devices` using `Trainer(accelerator='mps', devices=1)`.
  rank_zero_warn(

  | Name      | Type             | Params
-----------------------------------------------
0 | metamodel | SubtypeMetamodel | 8.8 K 
-----------------------------------------------
8.8 K     Trainable params
0         Non-trainable params
8.8 K     Total params
0.035     Total estimated model params size (MB)


Sanity Checking: 0it [00:00, ?it/s]

/opt/homebrew/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:236: PossibleUserWarning: The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 10 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
/opt/homebrew/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:236: PossibleUserWarning: The dataloader, train_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 10 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(


Training: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

GPU available: True (mps), used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs

  | Name      | Type             | Params
-----------------------------------------------
0 | metamodel | SubtypeMetamodel | 8.8 K 
-----------------------------------------------
8.8 K     Trainable params
0         Non-trainable params
8.8 K     Total params
0.035     Total estimated model params size (MB)


Sanity Checking: 0it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

GPU available: True (mps), used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs

  | Name      | Type             | Params
-----------------------------------------------
0 | metamodel | SubtypeMetamodel | 8.8 K 
-----------------------------------------------
8.8 K     Trainable params
0         Non-trainable params
8.8 K     Total params
0.035     Total estimated model params size (MB)


Sanity Checking: 0it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

/opt/homebrew/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:236: PossibleUserWarning: The dataloader, predict_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 10 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(


Predicting: 800it [00:00, ?it/s]

/opt/homebrew/lib/python3.10/site-packages/pytorch_lightning/loops/epoch/prediction_epoch_loop.py:174: UserWarning: Lightning couldn't infer the indices fetched for your dataloader.
  warning_cache.warn("Lightning couldn't infer the indices fetched for your dataloader.")


Predicting: 800it [00:00, ?it/s]

Predicting: 800it [00:00, ?it/s]

Predicting: 800it [00:00, ?it/s]

Predicting: 800it [00:00, ?it/s]

Predicting: 800it [00:00, ?it/s]

array([[[[8.90472186e-01, 4.19935115e-03, 8.89287959e-03, ...,
          2.03102049e-03, 1.44963386e-03, 5.05019217e-05],
         [4.38308853e-03, 8.98945433e-01, 6.48138349e-03, ...,
          6.16321081e-03, 3.41221684e-03, 1.48194795e-03],
         [8.04615389e-03, 5.77174339e-03, 8.83806640e-01, ...,
          1.30990089e-04, 7.15085060e-04, 1.09472699e-04],
         ...,
         [1.93473576e-03, 5.51280105e-03, 1.64424065e-04, ...,
          8.96431582e-01, 9.71804769e-06, 7.94839776e-05],
         [1.76587424e-03, 3.32553254e-03, 4.44663068e-04, ...,
          5.68022680e-07, 8.82335664e-01, 1.23784542e-03],
         [6.17120277e-05, 1.12446005e-03, 1.30225248e-04, ...,
          3.44289699e-05, 1.19242039e-03, 8.94714563e-01]],

        [[9.57419341e-01, 5.10498255e-03, 9.59237892e-03, ...,
          2.06023237e-03, 1.44386713e-03, 9.04935194e-05],
         [5.45712742e-03, 9.59956504e-01, 7.48704892e-03, ...,
          7.09678883e-03, 4.93112584e-03, 2.09458947e-03],
        

In [4]:
# Markov Networks

from contextualized.easy import ContextualizedMarkovNetworks

cmn = ContextualizedMarkovNetworks(encoder_type='ngam', num_archetypes=16, n_bootstraps=3)
cmn.fit(C, X, max_epochs=5)

# Get network
cmn.predict_networks(C)

# Get precision matrices
cmn.predict_precisions(C)



GPU available: True (mps), used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs

  | Name      | Type             | Params
-----------------------------------------------
0 | metamodel | SubtypeMetamodel | 7.3 K 
-----------------------------------------------
7.3 K     Trainable params
0         Non-trainable params
7.3 K     Total params
0.029     Total estimated model params size (MB)


Sanity Checking: 0it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

GPU available: True (mps), used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs

  | Name      | Type             | Params
-----------------------------------------------
0 | metamodel | SubtypeMetamodel | 7.3 K 
-----------------------------------------------
7.3 K     Trainable params
0         Non-trainable params
7.3 K     Total params
0.029     Total estimated model params size (MB)


Sanity Checking: 0it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

GPU available: True (mps), used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs

  | Name      | Type             | Params
-----------------------------------------------
0 | metamodel | SubtypeMetamodel | 7.3 K 
-----------------------------------------------
7.3 K     Trainable params
0         Non-trainable params
7.3 K     Total params
0.029     Total estimated model params size (MB)


Sanity Checking: 0it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Predicting: 800it [00:00, ?it/s]

Predicting: 800it [00:00, ?it/s]

Predicting: 800it [00:00, ?it/s]

Predicting: 800it [00:00, ?it/s]

Predicting: 800it [00:00, ?it/s]

Predicting: 800it [00:00, ?it/s]

Predicting: 800it [00:00, ?it/s]

Predicting: 800it [00:00, ?it/s]

Predicting: 800it [00:00, ?it/s]

array([[[[-0.        ,  0.0361928 ,  0.05055533, ..., -0.03620366,
          -0.06385705,  0.00821517],
         [ 0.0361928 , -0.        ,  0.02504921, ...,  0.04703653,
           0.07361782,  0.00532985],
         [ 0.05055533,  0.02504921, -0.        , ...,  0.03320497,
          -0.05435441, -0.02971142],
         ...,
         [-0.03620366,  0.04703653,  0.03320497, ..., -0.        ,
          -0.080511  ,  0.03720195],
         [-0.06385705,  0.07361782, -0.05435441, ..., -0.080511  ,
          -0.        , -0.07560732],
         [ 0.00821517,  0.00532985, -0.02971142, ...,  0.03720195,
          -0.07560732, -0.        ]],

        [[-0.        ,  0.02224281,  0.08533681, ..., -0.03194305,
          -0.01507219, -0.03312518],
         [ 0.02224281, -0.        , -0.00159212, ...,  0.03859939,
           0.1040634 , -0.00371176],
         [ 0.08533681, -0.00159212, -0.        , ..., -0.01901687,
          -0.0491023 ,  0.03938597],
         ...,
         [-0.03194305,  0.03859939

In [6]:
# Bayesian Networks
from contextualized.easy import ContextualizedBayesianNetworks

cbn = ContextualizedMarkovNetworks(encoder_type='ngam', num_archetypes=16, n_bootstraps=3)
cbn.fit(C, X, max_epochs=5)

# Get network
cbn.predict_networks(C)


cbn.measure_mses(C, X)

GPU available: True (mps), used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
/opt/homebrew/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py:1789: UserWarning: MPS available but not used. Set `accelerator` and `devices` using `Trainer(accelerator='mps', devices=1)`.
  rank_zero_warn(

  | Name      | Type             | Params
-----------------------------------------------
0 | metamodel | SubtypeMetamodel | 7.3 K 
-----------------------------------------------
7.3 K     Trainable params
0         Non-trainable params
7.3 K     Total params
0.029     Total estimated model params size (MB)


Sanity Checking: 0it [00:00, ?it/s]

/opt/homebrew/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:236: PossibleUserWarning: The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 10 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
/opt/homebrew/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:236: PossibleUserWarning: The dataloader, train_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 10 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(


Training: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

GPU available: True (mps), used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs

  | Name      | Type             | Params
-----------------------------------------------
0 | metamodel | SubtypeMetamodel | 7.3 K 
-----------------------------------------------
7.3 K     Trainable params
0         Non-trainable params
7.3 K     Total params
0.029     Total estimated model params size (MB)


Sanity Checking: 0it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

GPU available: True (mps), used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs

  | Name      | Type             | Params
-----------------------------------------------
0 | metamodel | SubtypeMetamodel | 7.3 K 
-----------------------------------------------
7.3 K     Trainable params
0         Non-trainable params
7.3 K     Total params
0.029     Total estimated model params size (MB)


Sanity Checking: 0it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

/opt/homebrew/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:236: PossibleUserWarning: The dataloader, predict_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 10 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(


Predicting: 800it [00:00, ?it/s]

Predicting: 800it [00:00, ?it/s]

Predicting: 800it [00:00, ?it/s]

Predicting: 800it [00:00, ?it/s]

Predicting: 800it [00:00, ?it/s]

Predicting: 800it [00:00, ?it/s]

Predicting: 800it [00:00, ?it/s]

Predicting: 800it [00:00, ?it/s]

Predicting: 800it [00:00, ?it/s]

Predicting: 800it [00:00, ?it/s]

Predicting: 800it [00:00, ?it/s]

Predicting: 800it [00:00, ?it/s]

array([0.54485421, 1.03978218, 0.66372614, 1.17597379, 0.504791  ,
       1.01114918, 1.67300417, 0.95655705, 0.73110336, 0.95706395,
       1.21535534, 1.48580618, 2.29819609, 0.83228849, 0.70176657,
       1.1629574 , 1.49087037, 0.61031328, 0.62452267, 0.30892005,
       1.63473412, 1.21904678, 0.72700751, 0.35572999, 0.98981332,
       1.03351097, 1.10890939, 0.96714759, 0.77699085, 0.46416309,
       1.00367497, 0.36569367, 1.37600066, 1.2791138 , 0.68395544,
       0.91342834, 0.58620821, 0.63285201, 1.44327391, 1.33046884,
       0.50870534, 0.70636911, 0.58016588, 0.99198803, 0.91362459,
       1.53329891, 0.95759203, 2.12534793, 1.29161048, 0.2409306 ,
       1.73332616, 1.57019334, 0.99299952, 0.7031165 , 1.35496523,
       0.93233553, 0.72391034, 1.48846956, 0.61872322, 1.20978472,
       1.56052652, 0.96467016, 1.18314226, 1.2810026 , 1.20484058,
       1.36715227, 0.66035342, 0.89262136, 1.17217819, 0.65827154,
       0.92358028, 1.45637631, 0.82995517, 1.18625536, 1.05023